apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: azure-pipeline
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - git:
      repoURL: ssh://gitserver/example
      revision: main
      directories:
      - path: azure-pipelines/*
  template:
    metadata:
      name: 'azure-pipeline-{{path.basenameNormalized}}'
      namespace: argocd
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: azure-pipelines
      source:
        repoURL: ssh://gitserver/azure-pipeline
        targetRevision: main # same as generator
        path: '{{path}}' # the directory of current generator item
        helm:
          valueFiles:
          - values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
        - FailOnSharedResource=true
